name: "Setup Go Environment"
description: "Checkout code and set up Go with caching"
inputs:
  go-version:
    description: "Go version to use"
    required: false
    default: "^1.24"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
