name: Benchmark Logs

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [v1.3.0, v1.3.1, v1.4.0, v1.5.0, v1.6.0, v1.6.1, v1.7.0]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.tag }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run benchmarks
        uses: goptics/vizb@v0.10.0
        with:
          bench-cmd: "go test -bench=. -benchmem -cpu=1"
          tag: ${{ matrix.tag }}
          group-pattern: n/y
          name: "VarMQ Benchmark Log"
          output-json: output/${{ matrix.tag }}.json

      - uses: actions/upload-artifact@v4
        with:
          name: bench-${{ matrix.tag }}
          path: output/${{ matrix.tag }}.json

  merge:
    needs: bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: actions/download-artifact@v4
        with:
          path: results
          pattern: bench-*

      - name: Merge benchmark results
        uses: goptics/vizb@v0.10.0
        with:
          merge-dir: results
          tag-axis: x
          output-json: merged.json

      - uses: actions/upload-artifact@v4
        with:
          name: merged.json
          path: merged.json
