name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "docs/**"
      - "assets/**"
      - "LICENSE"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "docs/**"
      - "assets/**"
      - "LICENSE"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go Environment
        uses: ./.github/actions/setup-go

      - name: Run tests with coverage
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.txt
          verbose: true
  bench:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go Environment
        uses: ./.github/actions/setup-go

      - name: Run benchmark tests
        run: go test -bench=. -benchmem
